name: Download and Run EXE

on: workflow_dispatch

jobs:
  download-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download EXE file
      run: Invoke-WebRequest -Uri "https://cstore-pub-cos-seewo-report-tx.seewo.com/seewo-report_uwiwyizohhulnhlwhowojyjpyohhihhh?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDJUXMxJRLzPaeMp20jDSTFl23pLcdPwDF%26q-sign-time%3D1732786811%3B2048146811%26q-key-time%3D1732786811%3B2048146811%26q-header-list%3Dhost%26q-url-param-list%3Dresponse-content-disposition%26q-signature%3D7a2bfb215aafd3e099fbe5a8611af5e9b582bc85&response-content-disposition=attachment%3Bfilename%3D%22EasiNoteSetup_5.2.4.8615_seewo.exe%22%3Bfilename%2A%3Dutf-8%27%27EasiNoteSetup_5.2.4.8615_seewo.exe" -OutFile "EasiNoteSetup_5.2.4.8615_seewo.exe"

    - name: Run EXE file
      run: .\EasiNoteSetup_5.2.4.8615_seewo.exe

    - name: Install Git LFS
      run: |
        git lfs install
        git lfs track "*.exe"
        git add .gitattributes

    - name: Run script
      working-directory: ./Account Re-Acquisition
      run: python main.py

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Automated changes with Git LFS"
        git push https://x-access-token:${GH_PAT}@github.com/errorduplicator/Projects.git
