name: fetch
on: workflow_dispatch
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install pandas
  
    - name: Run script
      working-directory: ./news_acqusition_project
      run: python get_f10.py
    
    - name: Commit and push changes
      working-directory: ./news_acqusition_project
      run: |
        git config --global user.name 'errorduplicator'
        git config --global user.email 'friedrichswun@gmail.com'
        git add a.xlsx
        git commit -m "Update a.xlsx"
        git push
